#6 adds relatedItems and correct formatting of SeriesInformation.
BirkbeckCTP/datacite pull request #9
Opened 2024-02-22 17:11 UTC by ajrbyers

Closes #4 and Closes #6

2024-02-27 12:39 UTC, mauromsl approved these changes

2024-02-28 14:21 UTC, joemull requested changes
Haven't been able to review this fully yet because of some server access issues, but I will raise those in standup and in the meantime point out what might be a missing piece of data in the string formatting. See comment inline.

2024-02-28 14:25 UTC, ajrbyers commented on utils.py
>          )
Thanks Joe, actually its the last line of the `format` that has erroneously been left in place. I've added a commit to remove it.

2024-02-28 15:10 UTC, joemull approved these changes
Resolved the server issue and was able to complete review

2024-02-28 15:10 UTC, merged

2024-06-17 09:25 UTC, mattiker commented
Hello, I hope this is the right place for questions or suggestions related to this issue 😅
I think the changes are not live yet. Can you perhaps already say when or with which version the changes will be adopted?

I also have a small suggestion for improving the "formats" lines: https://github.com/BirkbeckCTP/datacite/blob/657fa6200ea96374aad691fd62fbb0628f9458ed/utils.py#L30-L34

Datacite advises to use file extension or MIME type: https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/format/#
So according to the [IANA media types](https://www.iana.org/assignments/media-types/media-types.xhtml), it should be:

- application/pdf
- application/xml

2024-06-17 09:29 UTC, ajrbyers commented
I've opened another PR for this here: https://github.com/BirkbeckCTP/datacite/pull/10